services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_DB: "$POSTGRES_DB"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  ldap:
    build:
      context: "$PWD/openldap"
      dockerfile: "$PWD/openldap/Dockerfile"
    container_name: openldap-server
    hostname: "ldap.${LDAP_DOMAIN}"
    restart: always
    environment:
      LDAP_ORGANISATION: "$LDAP_ORGANISATION"
      LDAP_DOMAIN: "$LDAP_DOMAIN"
      LDAP_ADMIN_PASSWORD: "$LDAP_ADMIN_PASSWORD"
      LDAP_BASE_DN: "$LDAP_BASE_DN"
      LDAP_TLS: false # TODO remove
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - "ldap_db:/var/lib/ldap"
      - "ldap_config:/etc/ldap/slapd.d"
    networks:
      - openldap

volumes:
  pgdata:
  ldap_db:
  ldap_config:
networks:
  openldap:
    name: openldap